### ISSUE TITLE
Need to ignore comment lines

### ISSUE THREAD

**Issue by evan-king** [Chocobo1/nppAutoDetectIndent#1]
Considering the following code snippet:

```php
class Example {
    
    /**
     * demonstrate
     * Define a function 
     * in a class
     * with a long description
     *
     * @param String input
     * @return void
     */
    public function demonstrate(String $input) {
        return null;
    }
    
}
```

nppAutoDetectIndent will consider files looking like this to have 5-space indentation because that is the most common indentation depth per unqualified line.  It should only be considering actual code lines, by excluding all comments (block or otherwise) and by extension lines that only consist of comments.

It would also be nice if we could override the derived value when said derivation is incorrect.

**Comment by Chocobo1** [comment]
>It should only be considering actual code lines,

I did run some tests but didn't found a reliable way to achieve this. I'll reconsider it when I have the need.

>It would also be nice if we could override the derived value when said derivation is incorrect.

Then it defeats the purpose of auto detecting. I plan to add an checkbox in the menu to disable the detection, so it fallback to the setting in Notepad++, I doubt it could be of much help.

**Comment by evan-king** [comment]
The plugin does indeed frequently mis-identify the indentation with or without interference by comment lines, and yes it does indeed defeat the purpose of using it.

I'm now left weighing the benefit of having it where it works against the lack of workaround where it doesn't.  If there is no plan to improve its robustness, the net benefit is looking increasingly dubious.

**Comment by Chocobo1** [comment]
> If there is no plan to improve its robustness, the net benefit is looking increasingly dubious.

Or you might improve the situation by submitting a PR ;)

**Comment by evan-king** [comment]
I don't normally do C++ work and don't have a win32 build environment/tool stack set up to test this out, but the following code theoretically works better.  Perhaps you would consider incorporating it in place of the existing `nppAutoDetectIndent::detectIndentSpaces`:

```cpp
const int MIN_INDENT = 2; // minimum width of a single indentation
const int MAX_INDENT = 8; // maximum width of a single indentation

const int MIN_DEPTH = MIN_INDENT; // ignore lines below this indentation level
const int MAX_DEPTH = 3*MAX_INDENT; // ignore lines beyond this indentation level

const int Lines = (std::max)(int(sciCall(SCI_GETLINECOUNT)), MAX_LINES);
const float Grace = lines / 50.0;

int frequency[MAX_DEPTH+1] = {0}; // indentation => count(lines of that exact indentation)
int margin[MAX_INDENT+1] = {0}; // indentation => count(lines with incompatible indentation)

// track frequency of lines fitting each exacat indentation level between DEPTH limits
for(int i = 0; i < Lines; i++) {
    const int indentWidth = int(sciCall(SCI_GETLINEINDENTATION, i));
    if(indentWidth != max(MIN_DEPTH, min(indentWidth, MAX_DEPTH))) continue;
    frequency[indentWidth]++;
}

// every counted line incompatible with this indentation level increases margin by one
for(int i = MIN_DEPTH; i <= MAX_DEPTH; i++) {
    for(int k = MIN_INDENT; k <= MAX_INDENT; k++) {
        if(i % k == 0) continue;
        margin[i] += frequency[k];
    }
}

// choose the last indent with the smallest margin (ties go to larger indent)
// Considers margins within Grace of zero as =zero,
// so occasional typos don't force smaller indentation
int which = MIN_INDENT;
for(int i = MIN_INDENT; i <= MAX_INDENT; i++) {
    if(frequency[i] == 0) continue;
    if(margin[i] <= margin[which] || margin[i] < Grace) which = i;
}

return which;
```

Given my lack of tooling this is not robustly tested by any stretch, but here are a couple scenarios (from real-world cases) where its hand-calculated result is more accurate:

<pre>
CASE 1

total lines: 128
indent: frequency (margin)
    0: 5 (ignored as below MIN_DEPTH)
    1: 14 (from comment blocks, ignored as below MIN_DEPTH)
    ----
    2: 0 (margin of 0)
    3: 0 (margin of 115)
    4: 11 (margin of 0)
    5: 0 (margin of 128) // and same for all remaining non-occurring levels
    8: 83 (margin of 24)
    12*: 13 (margin of 94)
    16*: 2 (margin of 107)
result: 4 (with a margin of 0)
my detection: 4, yours: 8


CASE 2

total lines: 214
indent: frequency (margin)
    0: 26 (ignored as below MIN)
    1: 0
    ----
    4: 3 (margin of 91)
    8: 50 (margin of 125)
    9*: 91 (all comment blocks, NOT ignored, but margin of 104)
    12*: 28 (margin of 167)
    16*: 20 (margin of 175)
    20*: 3 (margin of 192)
result: 4 (with a margin of 91 - would be 0 if excluding comments)
my detection: 4, yours: 9

</pre>
*: indentation levels with a * are not even counted as a candidate (exceeding MAX_INDENT) but would not not have been selected anyway (they are excluded for both efficiency and sanity in bizarre cases).

I'm not even remotely equipped to get into the logistics of parsing out comments beyond acknowledging that Scintilla does not immediately appear to offer any straightforward aid in that regard.  In my opinion, a simple regex that only operates on the first MAX_DEPTH characters and blindly assumes lines starting with `*` continue a comment block (i.e. `/\s+(\*|\/\/|\/\*|\#)/`) would suffice (particularly since other forms of block comment such as in XML or HTML are unlikely to diverge from the proper indentation levels).

**Comment by evan-king** [comment]
Here's a couple more scenarios.
<pre>
CASE 3 // Case 2 plus one 3-character (erroneous) indent

total lines: 215
indent: frequency (margin)
    0: 26 (ignored as below MIN)
    1: 0
    ----
    3: 1 (margin of 76)
    4: 3 (margin of 92)
    8: 50 (margin of 126)
    9*: 91 (all comment blocks, NOT ignored, but margin of 104)
    12*: 28 (margin of 167)
    16*: 20 (margin of 176)
    20*: 3 (margin of 193)
result: 3 (with a margin of 76 - no longer able to overpower the voluminous comments because 3 and 4 share some common multiples)
my detection: 3, yours: still 9


CASE 4 // Case 2 plus 5 5-character indents (block comment at another level)

total lines: 215
indent: frequency (margin)
    0: 26 (ignored as below MIN)
    1: 0
    ----
    4: 3 (margin of 96)
    5: 5 (margin of 186)
    8: 50 (margin of 130)
    9*: 91 (all comment blocks, NOT ignored, but margin of 109)
    12*: 28 (margin of 172)
    16*: 20 (margin of 180)
    20*: 3 (margin of 192)
result: 4 (with a margin of 91 - would be 0 if excluding comments)
my detection: 4, yours: still 9
</pre>
To test more robustly I would need to implement the logic in another language where I can set up a test harness to process many sample files, but I definitely won't bother if you're not interested in adopting the C++ implementation of this algorithm.

**Comment by Chocobo1** [comment]
>The plugin does indeed frequently mis-identify the indentation with or without interference by comment lines

I don't have usage statistics from users and I believe neither do you, at least for now, the current calculation method suits my needs and perhaps a few others.
And the method isn't my original idea, it is adopted from Geany editor.

>theoretically works better

For your test cases maybe.
Let's say in test case 1, what if the majority non-comment code is actually indented by 8? Then do you prefer to tap TAB twice or just once?
(And why do you still need auto-detection when you already know the correct indention in these cases? An option to turn detection off will suit you better)

I see you're basically trying to use find the GCD and also modeling the statistics to fit your way. In many other cases, how can you be sure it performs better than the current one? Not to mention your method still messed up in test case 3 if I read correctly.

Anyway, the correct way is still ignore comment lines properly when doing the counting, but as I've said I've found no reliable way currently.

>but I definitely won't bother if you're not interested in adopting the C++ implementation of this algorithm.

It would be possible to add your method as another detection method, but so far I'm still not convinced. 
Yet reaching a conclusion and I'm suppose to decide adopting it, yeah bravo, good job selling your idea, just shove it down the throat whether others like it or not. If you mean it, then there is no point discussing further.

**Comment by evan-king** [comment]
I take it from your answer that you think trying to collaborate is a waste of your time (and apparently an affront to your ego), so I won't waste mine.  But just to answer this flippant remark:
> (And why do you still need auto-detection when you already know the correct indention in these cases? An option to turn detection off will suit you better)

By that logic your plugin _has no use case_ since the correct value is readily evident to human eyes in any remotely reasonable case.  Knowing the correct indentation doesn't mean it's the same as every other file of that type I might (even simultaneously) edit, across all projects and teams.  Yes EditorConfig is an option, but one with serious issues handling remote filesystems.

I'm glad it works fine for you.  Enjoy, I guess.

**Comment by Chocobo1** [comment]
@evan-king
>I take it from your answer that you think trying to collaborate is a waste of your time (and apparently an affront to your ego), so I won't waste mine.

Heh, I tried 2~3 paragraphs [trying to discuss](https://github.com/Chocobo1/nppAutoDetectIndent/issues/1#issuecomment-414770807), all got ignored.

>But just to answer this flippant remark:

Flippant? From what I [read](https://github.com/Chocobo1/nppAutoDetectIndent/issues/1#issuecomment-414666331), this plugin got most case wrong for you. Isn't it logical to ask what happened in your case?

>By that logic your plugin has no use case since the correct value is readily evident to human eyes in any remotely reasonable case. 

You talk rude all the way from the first post and has something to do with my ego, heh, typical.
And you didn't even realize you can fork it and change it as you like, instead you spend your time pretending to be my boss.

> Knowing the correct indentation doesn't mean it's the same as every other file of that type I might (even simultaneously) edit, across all projects and teams. 

Yeah too bad it didn't work for you and your team, really sorry, all my fault for releasing a plugin for free.

>I'm glad it works fine for you. Enjoy, I guess.

Thanks!
