### ISSUE TITLE
Work with backspace too

### ISSUE THREAD

**Issue by acuna-public** [Chocobo1/nppAutoDetectIndent#2]
Thanks for this great plugin, but what about remove characters? I'm using 2 spaces instead of tab, but Notepad++ don't understand it while backspace, so I compelled to press the backspace twice instead of once to remove characters. I hoped that yours plugin can do it out of the box( Do you planned to implement this? Thanks in advance.

**Comment by Chocobo1** [comment]
I like that behavior too. Done in b9603e87015dd7d45623533dcbafb6fa22ab9c6d.

**Comment by acuna-public** [comment]
Hello, ah, I'm so sorry because having an sertificate issue with mailbox which connected to this GitHub account and have not receive mails this weeks (it's not my primary one).

Thanks a lot, but can you add it to the NPP plugins manager because I can't compile it at this time?
