### ISSUE TITLE
Shift + Tab not working

### ISSUE THREAD

**Issue by Krazal** [Chocobo1/nppAutoDetectIndent#4]
Hi!

The plugin is amazing, but I think, the `SCI_SETTABINDENTS` (line #241) and `SCI_SETBACKSPACEUNINDENTS` (line #243) should leave as true, otherwise eg. the Shift + tab as unindent does not working.

https://github.com/Chocobo1/nppAutoDetectIndent/blob/fc7a03f7736b7818f35212f69dbcae279b540959/src/nppAutoDetectIndent.cpp#L241

https://github.com/Chocobo1/nppAutoDetectIndent/blob/fc7a03f7736b7818f35212f69dbcae279b540959/src/nppAutoDetectIndent.cpp#L243

**Comment by Chocobo1** [comment]
I don't use <kbd>Shift + tab</kbd> myself but I suppose you are right. And I just released 2.0 for it.
