### ISSUE TITLE
Crash on Notepad++ 8.3

### ISSUE THREAD

**Issue by vinsworldcom** [Chocobo1/nppAutoDetectIndent#5]
In case you missed it:

Due to the support 2GB files opening in [Notepad++ v8.3 x64 build](https://community.notepad-plus-plus.org/topic/22469/notepad-v8-2-2-release-candidate-5), the header Sci_Position.h in Notepad++ has been modified for adapting this need.
This change has caused the instability in some plugins.

The solution is quite simple - just replace Sci_Position.h by [the new one](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Sci_Position.h).
ref:
https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

You will also need to update types throughout your code if you are referring to Scintilla positions and text ranges.  Scintilla API calls that return positions should not use `int` but rather `Sci_Position` and text ranges should use `Sci_PositionCR`.

You use a text range for example in your [code](https://github.com/Chocobo1/nppAutoDetectIndent/blob/f9b232fb3c18f98ba3fda19df2633fbeeb8c7bb5/src/nppAutoDetectIndent.cpp#L101). 

Sorry for the inconvenience and thank you for your help.

Cheers.

**Comment by Chocobo1** [comment]
For anyone reading this, I released a new version a few days ago. I tested quickly on notepad++ 8.3 and it didn't crash anymore.

> You will also need to update types throughout your code if you are referring to Scintilla positions and text ranges. Scintilla API calls that return positions should not use `int` but rather `Sci_Position` and text ranges should use `Sci_PositionCR`.
> 
> You use a text range for example in your [code](https://github.com/Chocobo1/nppAutoDetectIndent/blob/f9b232fb3c18f98ba3fda19df2633fbeeb8c7bb5/src/nppAutoDetectIndent.cpp#L101).

Thanks for the notice, I didn't noticed that types have changed.
The mentioned code segment should be safe (from crashing) as the casting is for an unused return value.
I noticed that scintilla has introduced some updates on types since I wrote this plugin, I'll update them (and make a new release) in a few days.

**Comment by vinsworldcom** [comment]
Thank you for continued support of Notepad++ plugins!

**Comment by Chocobo1** [comment]
Done in 0b9e9b09f729e0fa5df19dbad99f6916ac0c0bf2.
